CREATE SEQUENCE SEQ_ALERTAS
       START WITH 1
       INCREMENT BY 1
       NOCACHE
       NOCYCLE;

CREATE TABLE T_ALERTAS(
    ID INTEGER DEFAULT SEQ_ALERTAS.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(256) NOT NULL,
    DT_LANCAMENTO DATE
);